export default{
  LOGIN:{
    START:"LOGIN_START",
    COMPLETE:"LOGIN_COMPLETE",
    ERROR:"LOGIN_ERROR"
  },
  FETCH_USERDATA:{
    START:"FETCH_USERDATA_START",
    COMPLETE:"FETCH_USERDATA_COMPLETE",
    ERROR:"FETCH_USERDATA_ERROR"
  },
  MATCH_ROOM:{
    START:"MATCH_ROOM_START",
    FOUND:"MATCH_ROOM_FOUND",
    NOT_FOUND:"MATCH_ROOM_NOT_FOUND",
    ERROR:"MATCH_ROOM_ERROR"
  },
  CREATE_ROOM:{
    START:"CREATE_ROOM_START",
    COMPLETE:"CREATE_ROOM_COMPLETE",
    ERROR:"CREATE_ROOM_ERROR"
  },

}
