export default{
  LOGIN:{
    START:"LOGIN_START",
    COMPLETE:"LOGIN_COMPLETE",
    ERROR:"LOGIN_ERROR"
  },
  FETCH_USERDATA:{
    START:"FETCH_USERDATA_START",
    COMPLETE:"FETCH_USERDATA_COMPLETE",
    ERROR:"FETCH_USERDATA_ERROR"
  }
}
